##############Requests using REST CLIENT in vscode##############

###########Get all contacts###########
###Localhost###########
    GET http://localhost:3000/contacts
###On server###########
    GET https://cse-341-project1-7pk9.onrender.com/contacts

###########Get a contact by id###########
###Localhost###########
    GET http://localhost:3000/contacts/66686d80f56eb6d8692b3c11
###On server###########
    GET https://cse-341-project1-7pk9.onrender.com/contacts/66686d80f56eb6d8692b3c11