##############Requests using REST CLIENT in vscode##############

###########Get all contacts###########
###Localhost###########
GET http://localhost:3000/contacts
###On server###########
GET https://cse-341-project1-reva.onrender.com/contacts

###########Get a contact by id###########
###Localhost###########
GET http://localhost:3000/contacts/66744ae4ebb64be2b8c9d80c
###On server###########
GET https://cse-341-project1-reva.onrender.com/contacts/66744ae4ebb64be2b8c9d80c

###########Create a contact###########
###Localhost###########
POST http://localhost:3000/contacts
Content-Type: application/json

    {
        "firstName": "Pepe",
        "lastName": "Saggeth",
        "email": "julian.saggeth@gmail.com",
        "favoriteColor": "pink",
        "birthday": "1975-10-28"
    }
###On server###########
POST https://cse-341-project1-reva.onrender.com/contacts
Content-Type: application/json

    {
        "firstName": "Pedro",
        "lastName": "Saggeth",
        "email": "pedro.saggeth@gmail.com",
        "favoriteColor": "pink",
        "birthday": "1975-10-28"
    }

###########Update a contact###########
###Localhost###########
PUT http://localhost:3000/contacts/6676b0f0282c159c86e4fe21
Content-Type: application/json

    {
        "favoriteColor": "red"
    }

###On server###########
PUT https://cse-341-project1-reva.onrender.com/contacts/66744ae4ebb64be2b8c9d80c
Content-Type: application/json

    {
        "favoriteColor": "green"
    }

###########Delete a contact###########
###Localhost###########
DELETE http://localhost:3000/contacts/6676b0f0282c159c86e4fe21

###On server###########
DELETE https://cse-341-project1-reva.onrender.com/contacts/66745e9e194c97788207e90a